
// This file has been generated by the GUI designer. Do not modify.
namespace fit.gui.gtk
{
	public partial class TestsFolder
	{
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Table table1;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.Entry entryFolderName;
		private global::Gtk.Entry entryFixturesDirectoryPath;
		private global::Gtk.Entry entryResultsDirectoryPath;
		private global::Gtk.Entry entrySpecificationsDirectoryPath;
		private global::Gtk.FileChooserButton filechooserbuttonFixturesDirectoryPath;
		private global::Gtk.FileChooserButton filechooserbuttonResultsDirectoryPath;
		private global::Gtk.FileChooserButton filechooserbuttonSpecificationsDirectoryPath;
		private global::Gtk.Label labelFixturesDirectoryPath;
		private global::Gtk.Label labelFolderName;
		private global::Gtk.Label labelResultsDirectoryPath;
		private global::Gtk.Label labelSpecificationsDirectoryPath;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget fit.gui.gtk.TestsFolder
			this.Name = "fit.gui.gtk.TestsFolder";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child fit.gui.gtk.TestsFolder.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.TopPadding = ((uint)(10));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.alignment3.RightPadding = ((uint)(10));
			// Container child alignment3.Gtk.Container+ContainerChild
			this.entryFolderName = new global::Gtk.Entry ();
			this.entryFolderName.CanFocus = true;
			this.entryFolderName.Name = "entryFolderName";
			this.entryFolderName.IsEditable = true;
			this.entryFolderName.InvisibleChar = '•';
			this.alignment3.Add (this.entryFolderName);
			this.table1.Add (this.alignment3);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment3]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryFixturesDirectoryPath = new global::Gtk.Entry ();
			this.entryFixturesDirectoryPath.CanFocus = true;
			this.entryFixturesDirectoryPath.Name = "entryFixturesDirectoryPath";
			this.entryFixturesDirectoryPath.IsEditable = true;
			this.entryFixturesDirectoryPath.InvisibleChar = '•';
			this.table1.Add (this.entryFixturesDirectoryPath);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryFixturesDirectoryPath]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryResultsDirectoryPath = new global::Gtk.Entry ();
			this.entryResultsDirectoryPath.CanFocus = true;
			this.entryResultsDirectoryPath.Name = "entryResultsDirectoryPath";
			this.entryResultsDirectoryPath.IsEditable = true;
			this.entryResultsDirectoryPath.InvisibleChar = '•';
			this.table1.Add (this.entryResultsDirectoryPath);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryResultsDirectoryPath]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entrySpecificationsDirectoryPath = new global::Gtk.Entry ();
			this.entrySpecificationsDirectoryPath.CanFocus = true;
			this.entrySpecificationsDirectoryPath.Name = "entrySpecificationsDirectoryPath";
			this.entrySpecificationsDirectoryPath.IsEditable = true;
			this.entrySpecificationsDirectoryPath.InvisibleChar = '•';
			this.table1.Add (this.entrySpecificationsDirectoryPath);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.entrySpecificationsDirectoryPath]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.filechooserbuttonFixturesDirectoryPath = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a Folder"), ((global::Gtk.FileChooserAction)(2)));
			this.filechooserbuttonFixturesDirectoryPath.Name = "filechooserbuttonFixturesDirectoryPath";
			this.filechooserbuttonFixturesDirectoryPath.ShowHidden = true;
			this.table1.Add (this.filechooserbuttonFixturesDirectoryPath);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.filechooserbuttonFixturesDirectoryPath]));
			w7.TopAttach = ((uint)(3));
			w7.BottomAttach = ((uint)(4));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XPadding = ((uint)(10));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.filechooserbuttonResultsDirectoryPath = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a Folder"), ((global::Gtk.FileChooserAction)(2)));
			this.filechooserbuttonResultsDirectoryPath.Name = "filechooserbuttonResultsDirectoryPath";
			this.filechooserbuttonResultsDirectoryPath.ShowHidden = true;
			this.table1.Add (this.filechooserbuttonResultsDirectoryPath);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.filechooserbuttonResultsDirectoryPath]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.LeftAttach = ((uint)(2));
			w8.RightAttach = ((uint)(3));
			w8.XPadding = ((uint)(10));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.filechooserbuttonSpecificationsDirectoryPath = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a Folder"), ((global::Gtk.FileChooserAction)(2)));
			this.filechooserbuttonSpecificationsDirectoryPath.Name = "filechooserbuttonSpecificationsDirectoryPath";
			this.filechooserbuttonSpecificationsDirectoryPath.ShowHidden = true;
			this.table1.Add (this.filechooserbuttonSpecificationsDirectoryPath);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.filechooserbuttonSpecificationsDirectoryPath]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.XPadding = ((uint)(10));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelFixturesDirectoryPath = new global::Gtk.Label ();
			this.labelFixturesDirectoryPath.Name = "labelFixturesDirectoryPath";
			this.labelFixturesDirectoryPath.Xalign = 0F;
			this.labelFixturesDirectoryPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Results Directory Path");
			this.table1.Add (this.labelFixturesDirectoryPath);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelFixturesDirectoryPath]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.XPadding = ((uint)(10));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelFolderName = new global::Gtk.Label ();
			this.labelFolderName.Name = "labelFolderName";
			this.labelFolderName.Xalign = 0F;
			this.labelFolderName.LabelProp = global::Mono.Unix.Catalog.GetString ("UI Folder Name");
			this.labelFolderName.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add (this.labelFolderName);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelFolderName]));
			w11.XPadding = ((uint)(10));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelResultsDirectoryPath = new global::Gtk.Label ();
			this.labelResultsDirectoryPath.Name = "labelResultsDirectoryPath";
			this.labelResultsDirectoryPath.Xalign = 0F;
			this.labelResultsDirectoryPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Results Directory Path");
			this.table1.Add (this.labelResultsDirectoryPath);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelResultsDirectoryPath]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XPadding = ((uint)(10));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelSpecificationsDirectoryPath = new global::Gtk.Label ();
			this.labelSpecificationsDirectoryPath.Name = "labelSpecificationsDirectoryPath";
			this.labelSpecificationsDirectoryPath.Xalign = 0F;
			this.labelSpecificationsDirectoryPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Specifications Directory Path");
			this.table1.Add (this.labelSpecificationsDirectoryPath);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelSpecificationsDirectoryPath]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.XPadding = ((uint)(10));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.alignment1.Add (this.table1);
			w1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(w1 [this.alignment1]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Internal child fit.gui.gtk.TestsFolder.ActionArea
			global::Gtk.HButtonBox w16 = this.ActionArea;
			w16.Name = "dialog1_ActionArea";
			w16.Spacing = 5;
			w16.BorderWidth = ((uint)(10));
			w16.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w16 [this.buttonCancel]));
			w17.Expand = false;
			w17.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w16 [this.buttonOk]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 782;
			this.DefaultHeight = 203;
			this.Show ();
			this.filechooserbuttonSpecificationsDirectoryPath.SelectionChanged += new global::System.EventHandler (this.OnSpecificationsDirectoryPathSelectionChanged);
			this.filechooserbuttonResultsDirectoryPath.SelectionChanged += new global::System.EventHandler (this.OnResultsDirectoryPathSelectionChanged);
			this.filechooserbuttonFixturesDirectoryPath.SelectionChanged += new global::System.EventHandler (this.OnFixturesDirectoryPathSelectionChanged);
			this.entrySpecificationsDirectoryPath.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSpecificationsDirectoryPathFocusOutEvent);
			this.entryResultsDirectoryPath.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnResultsDirectoryPathFocusOutEvent);
			this.entryFixturesDirectoryPath.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnFixturesDirectoryPathFocusOutevent);
		}
	}
}
