
// This file has been generated by the GUI designer. Do not modify.
namespace fit.gui.gtk
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button buttonStartStop;
		private global::Gtk.ProgressBar progressbarMain;
		private global::Gtk.Button buttonDeleteFolder;
		private global::Gtk.Button buttonEditFolder;
		private global::Gtk.Button buttonAddFolder;
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeview1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox2;
		private global::Gtk.ToggleButton togglebuttonShowSpecification;
		private global::Gtk.ToggleButton togglebuttonShowResult;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget fit.gui.gtk.MainWindow
			this.Name = "fit.gui.gtk.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child fit.gui.gtk.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(5));
			this.alignment2.TopPadding = ((uint)(5));
			this.alignment2.RightPadding = ((uint)(5));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonStartStop = new global::Gtk.Button ();
			this.buttonStartStop.TooltipMarkup = "XXX";
			this.buttonStartStop.WidthRequest = 100;
			this.buttonStartStop.CanFocus = true;
			this.buttonStartStop.Name = "buttonStartStop";
			this.buttonStartStop.UseUnderline = true;
			// Container child buttonStartStop.Gtk.Container+ContainerChild
			global::Gtk.Alignment w1 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w2 = new global::Gtk.HBox ();
			w2.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("fit.gui.gtk.control_play_blue.png");
			w2.Add (w3);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w5 = new global::Gtk.Label ();
			w5.LabelProp = global::Mono.Unix.Catalog.GetString ("_Start");
			w5.UseUnderline = true;
			w2.Add (w5);
			w1.Add (w2);
			this.buttonStartStop.Add (w1);
			this.hbox1.Add (this.buttonStartStop);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonStartStop]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.progressbarMain = new global::Gtk.ProgressBar ();
			this.progressbarMain.Name = "progressbarMain";
			this.progressbarMain.Text = "";
			this.hbox1.Add (this.progressbarMain);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.progressbarMain]));
			w10.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonDeleteFolder = new global::Gtk.Button ();
			this.buttonDeleteFolder.TooltipMarkup = "Delete test folder";
			this.buttonDeleteFolder.WidthRequest = 100;
			this.buttonDeleteFolder.CanFocus = true;
			this.buttonDeleteFolder.Name = "buttonDeleteFolder";
			this.buttonDeleteFolder.UseUnderline = true;
			// Container child buttonDeleteFolder.Gtk.Container+ContainerChild
			global::Gtk.Alignment w11 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w12 = new global::Gtk.HBox ();
			w12.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("fit.gui.gtk.folder_delete.png");
			w12.Add (w13);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w15 = new global::Gtk.Label ();
			w15.LabelProp = global::Mono.Unix.Catalog.GetString ("Delete");
			w15.UseUnderline = true;
			w12.Add (w15);
			w11.Add (w12);
			this.buttonDeleteFolder.Add (w11);
			this.hbox1.Add (this.buttonDeleteFolder);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonDeleteFolder]));
			w19.PackType = ((global::Gtk.PackType)(1));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonEditFolder = new global::Gtk.Button ();
			this.buttonEditFolder.TooltipMarkup = "Edit test folder";
			this.buttonEditFolder.WidthRequest = 100;
			this.buttonEditFolder.CanFocus = true;
			this.buttonEditFolder.Name = "buttonEditFolder";
			this.buttonEditFolder.UseUnderline = true;
			// Container child buttonEditFolder.Gtk.Container+ContainerChild
			global::Gtk.Alignment w20 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w21 = new global::Gtk.HBox ();
			w21.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w22 = new global::Gtk.Image ();
			w22.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("fit.gui.gtk.folder.png");
			w21.Add (w22);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w24 = new global::Gtk.Label ();
			w24.LabelProp = global::Mono.Unix.Catalog.GetString ("Edit");
			w24.UseUnderline = true;
			w21.Add (w24);
			w20.Add (w21);
			this.buttonEditFolder.Add (w20);
			this.hbox1.Add (this.buttonEditFolder);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonEditFolder]));
			w28.PackType = ((global::Gtk.PackType)(1));
			w28.Position = 3;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonAddFolder = new global::Gtk.Button ();
			this.buttonAddFolder.TooltipMarkup = "Add new test folder";
			this.buttonAddFolder.WidthRequest = 100;
			this.buttonAddFolder.CanFocus = true;
			this.buttonAddFolder.Name = "buttonAddFolder";
			this.buttonAddFolder.UseUnderline = true;
			// Container child buttonAddFolder.Gtk.Container+ContainerChild
			global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w30 = new global::Gtk.HBox ();
			w30.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w31 = new global::Gtk.Image ();
			w31.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("fit.gui.gtk.folder_add.png");
			w30.Add (w31);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w33 = new global::Gtk.Label ();
			w33.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
			w33.UseUnderline = true;
			w30.Add (w33);
			w29.Add (w30);
			this.buttonAddFolder.Add (w29);
			this.hbox1.Add (this.buttonAddFolder);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonAddFolder]));
			w37.PackType = ((global::Gtk.PackType)(1));
			w37.Position = 4;
			w37.Expand = false;
			w37.Fill = false;
			this.alignment2.Add (this.hbox1);
			this.vbox1.Add (this.alignment2);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment2]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 172;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add (this.treeview1);
			this.hpaned1.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w41 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow]));
			w41.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.togglebuttonShowSpecification = new global::Gtk.ToggleButton ();
			this.togglebuttonShowSpecification.WidthRequest = 180;
			this.togglebuttonShowSpecification.CanFocus = true;
			this.togglebuttonShowSpecification.Name = "togglebuttonShowSpecification";
			this.togglebuttonShowSpecification.UseUnderline = true;
			this.togglebuttonShowSpecification.Active = true;
			// Container child togglebuttonShowSpecification.Gtk.Container+ContainerChild
			global::Gtk.Alignment w42 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w43 = new global::Gtk.HBox ();
			w43.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w44 = new global::Gtk.Image ();
			w44.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-file", global::Gtk.IconSize.Menu);
			w43.Add (w44);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w46 = new global::Gtk.Label ();
			w46.LabelProp = global::Mono.Unix.Catalog.GetString ("Show specification");
			w46.UseUnderline = true;
			w43.Add (w46);
			w42.Add (w43);
			this.togglebuttonShowSpecification.Add (w42);
			this.hbox2.Add (this.togglebuttonShowSpecification);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.togglebuttonShowSpecification]));
			w50.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.togglebuttonShowResult = new global::Gtk.ToggleButton ();
			this.togglebuttonShowResult.WidthRequest = 180;
			this.togglebuttonShowResult.CanFocus = true;
			this.togglebuttonShowResult.Name = "togglebuttonShowResult";
			this.togglebuttonShowResult.UseUnderline = true;
			// Container child togglebuttonShowResult.Gtk.Container+ContainerChild
			global::Gtk.Alignment w51 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w52 = new global::Gtk.HBox ();
			w52.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w53 = new global::Gtk.Image ();
			w53.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			w52.Add (w53);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w55 = new global::Gtk.Label ();
			w55.LabelProp = global::Mono.Unix.Catalog.GetString ("Show result");
			w55.UseUnderline = true;
			w52.Add (w55);
			w51.Add (w52);
			this.togglebuttonShowResult.Add (w51);
			this.hbox2.Add (this.togglebuttonShowResult);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.togglebuttonShowResult]));
			w59.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w60.Position = 0;
			w60.Expand = false;
			w60.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.vbox3.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.scrolledwindow1]));
			w61.Position = 1;
			this.hpaned1.Add (this.vbox3);
			this.vbox1.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
			w63.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 584;
			this.DefaultHeight = 284;
			this.Hide ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.buttonStartStop.Clicked += new global::System.EventHandler (this.OnButtonStartStopClicked);
			this.buttonAddFolder.Clicked += new global::System.EventHandler (this.OnButtonAddFolderClicked);
			this.buttonEditFolder.Clicked += new global::System.EventHandler (this.OnButtonAddFolderClicked);
			this.buttonDeleteFolder.Clicked += new global::System.EventHandler (this.OnButtonAddFolderClicked);
			this.togglebuttonShowSpecification.Clicked += new global::System.EventHandler (this.OnTogglebuttonShowSpecificationClicked);
			this.togglebuttonShowResult.Clicked += new global::System.EventHandler (this.OnTogglebuttonShowResultClicked);
		}
	}
}
