
// This file has been generated by the GUI designer. Do not modify.
namespace fit.gui.gtk
{
	public partial class TestsFolder
	{
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Table table1;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.Entry entryFolderName;
		private global::Gtk.Button buttonFixturesDirectoryPath;
		private global::Gtk.Button buttonResultsDirectoryPath;
		private global::Gtk.Button buttonSpecificationsDirectoryPath;
		private global::Gtk.Entry entryFixturesDirectoryPath;
		private global::Gtk.Entry entryResultsDirectoryPath;
		private global::Gtk.Entry entrySpecificationsDirectoryPath;
		private global::Gtk.Label labelFixturesDirectoryPath;
		private global::Gtk.Label labelFolderName;
		private global::Gtk.Label labelResultsDirectoryPath;
		private global::Gtk.Label labelSpecificationsDirectoryPath;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget fit.gui.gtk.TestsFolder
			this.Name = "fit.gui.gtk.TestsFolder";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child fit.gui.gtk.TestsFolder.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.TopPadding = ((uint)(10));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.alignment3.RightPadding = ((uint)(10));
			// Container child alignment3.Gtk.Container+ContainerChild
			this.entryFolderName = new global::Gtk.Entry ();
			this.entryFolderName.CanFocus = true;
			this.entryFolderName.Name = "entryFolderName";
			this.entryFolderName.IsEditable = true;
			this.entryFolderName.InvisibleChar = '•';
			this.alignment3.Add (this.entryFolderName);
			this.table1.Add (this.alignment3);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment3]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonFixturesDirectoryPath = new global::Gtk.Button ();
			this.buttonFixturesDirectoryPath.CanFocus = true;
			this.buttonFixturesDirectoryPath.Name = "buttonFixturesDirectoryPath";
			this.buttonFixturesDirectoryPath.UseUnderline = true;
			// Container child buttonFixturesDirectoryPath.Gtk.Container+ContainerChild
			global::Gtk.Alignment w4 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w5 = new global::Gtk.HBox ();
			w5.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_folder", global::Gtk.IconSize.Menu);
			w5.Add (w6);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w8 = new global::Gtk.Label ();
			w8.LabelProp = global::Mono.Unix.Catalog.GetString ("_Select...");
			w8.UseUnderline = true;
			w5.Add (w8);
			w4.Add (w5);
			this.buttonFixturesDirectoryPath.Add (w4);
			this.table1.Add (this.buttonFixturesDirectoryPath);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonFixturesDirectoryPath]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.XPadding = ((uint)(10));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonResultsDirectoryPath = new global::Gtk.Button ();
			this.buttonResultsDirectoryPath.CanFocus = true;
			this.buttonResultsDirectoryPath.Name = "buttonResultsDirectoryPath";
			this.buttonResultsDirectoryPath.UseUnderline = true;
			// Container child buttonResultsDirectoryPath.Gtk.Container+ContainerChild
			global::Gtk.Alignment w13 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w14 = new global::Gtk.HBox ();
			w14.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w15 = new global::Gtk.Image ();
			w15.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_folder", global::Gtk.IconSize.Menu);
			w14.Add (w15);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w17 = new global::Gtk.Label ();
			w17.LabelProp = global::Mono.Unix.Catalog.GetString ("_Select...");
			w17.UseUnderline = true;
			w14.Add (w17);
			w13.Add (w14);
			this.buttonResultsDirectoryPath.Add (w13);
			this.table1.Add (this.buttonResultsDirectoryPath);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonResultsDirectoryPath]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.LeftAttach = ((uint)(2));
			w21.RightAttach = ((uint)(3));
			w21.XPadding = ((uint)(10));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonSpecificationsDirectoryPath = new global::Gtk.Button ();
			this.buttonSpecificationsDirectoryPath.CanFocus = true;
			this.buttonSpecificationsDirectoryPath.Name = "buttonSpecificationsDirectoryPath";
			this.buttonSpecificationsDirectoryPath.UseUnderline = true;
			// Container child buttonSpecificationsDirectoryPath.Gtk.Container+ContainerChild
			global::Gtk.Alignment w22 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w23 = new global::Gtk.HBox ();
			w23.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w24 = new global::Gtk.Image ();
			w24.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_folder", global::Gtk.IconSize.Menu);
			w23.Add (w24);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w26 = new global::Gtk.Label ();
			w26.LabelProp = global::Mono.Unix.Catalog.GetString ("_Select...");
			w26.UseUnderline = true;
			w23.Add (w26);
			w22.Add (w23);
			this.buttonSpecificationsDirectoryPath.Add (w22);
			this.table1.Add (this.buttonSpecificationsDirectoryPath);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonSpecificationsDirectoryPath]));
			w30.TopAttach = ((uint)(1));
			w30.BottomAttach = ((uint)(2));
			w30.LeftAttach = ((uint)(2));
			w30.RightAttach = ((uint)(3));
			w30.XPadding = ((uint)(10));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryFixturesDirectoryPath = new global::Gtk.Entry ();
			this.entryFixturesDirectoryPath.CanFocus = true;
			this.entryFixturesDirectoryPath.Name = "entryFixturesDirectoryPath";
			this.entryFixturesDirectoryPath.IsEditable = true;
			this.entryFixturesDirectoryPath.InvisibleChar = '•';
			this.table1.Add (this.entryFixturesDirectoryPath);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryFixturesDirectoryPath]));
			w31.TopAttach = ((uint)(3));
			w31.BottomAttach = ((uint)(4));
			w31.LeftAttach = ((uint)(1));
			w31.RightAttach = ((uint)(2));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryResultsDirectoryPath = new global::Gtk.Entry ();
			this.entryResultsDirectoryPath.CanFocus = true;
			this.entryResultsDirectoryPath.Name = "entryResultsDirectoryPath";
			this.entryResultsDirectoryPath.IsEditable = true;
			this.entryResultsDirectoryPath.InvisibleChar = '•';
			this.table1.Add (this.entryResultsDirectoryPath);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryResultsDirectoryPath]));
			w32.TopAttach = ((uint)(2));
			w32.BottomAttach = ((uint)(3));
			w32.LeftAttach = ((uint)(1));
			w32.RightAttach = ((uint)(2));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entrySpecificationsDirectoryPath = new global::Gtk.Entry ();
			this.entrySpecificationsDirectoryPath.CanFocus = true;
			this.entrySpecificationsDirectoryPath.Name = "entrySpecificationsDirectoryPath";
			this.entrySpecificationsDirectoryPath.IsEditable = true;
			this.entrySpecificationsDirectoryPath.InvisibleChar = '•';
			this.table1.Add (this.entrySpecificationsDirectoryPath);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1 [this.entrySpecificationsDirectoryPath]));
			w33.TopAttach = ((uint)(1));
			w33.BottomAttach = ((uint)(2));
			w33.LeftAttach = ((uint)(1));
			w33.RightAttach = ((uint)(2));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelFixturesDirectoryPath = new global::Gtk.Label ();
			this.labelFixturesDirectoryPath.Name = "labelFixturesDirectoryPath";
			this.labelFixturesDirectoryPath.Xalign = 0F;
			this.labelFixturesDirectoryPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Fixtures Directory Path");
			this.table1.Add (this.labelFixturesDirectoryPath);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelFixturesDirectoryPath]));
			w34.TopAttach = ((uint)(3));
			w34.BottomAttach = ((uint)(4));
			w34.XPadding = ((uint)(10));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelFolderName = new global::Gtk.Label ();
			this.labelFolderName.Name = "labelFolderName";
			this.labelFolderName.Xalign = 0F;
			this.labelFolderName.LabelProp = global::Mono.Unix.Catalog.GetString ("UI Folder Name");
			this.labelFolderName.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add (this.labelFolderName);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelFolderName]));
			w35.XPadding = ((uint)(10));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelResultsDirectoryPath = new global::Gtk.Label ();
			this.labelResultsDirectoryPath.Name = "labelResultsDirectoryPath";
			this.labelResultsDirectoryPath.Xalign = 0F;
			this.labelResultsDirectoryPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Results Directory Path");
			this.table1.Add (this.labelResultsDirectoryPath);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelResultsDirectoryPath]));
			w36.TopAttach = ((uint)(2));
			w36.BottomAttach = ((uint)(3));
			w36.XPadding = ((uint)(10));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelSpecificationsDirectoryPath = new global::Gtk.Label ();
			this.labelSpecificationsDirectoryPath.Name = "labelSpecificationsDirectoryPath";
			this.labelSpecificationsDirectoryPath.Xalign = 0F;
			this.labelSpecificationsDirectoryPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Specifications Directory Path");
			this.table1.Add (this.labelSpecificationsDirectoryPath);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelSpecificationsDirectoryPath]));
			w37.TopAttach = ((uint)(1));
			w37.BottomAttach = ((uint)(2));
			w37.XPadding = ((uint)(10));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			this.alignment1.Add (this.table1);
			w1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(w1 [this.alignment1]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Internal child fit.gui.gtk.TestsFolder.ActionArea
			global::Gtk.HButtonBox w40 = this.ActionArea;
			w40.Name = "dialog1_ActionArea";
			w40.Spacing = 5;
			w40.BorderWidth = ((uint)(10));
			w40.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w41 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w40 [this.buttonCancel]));
			w41.Expand = false;
			w41.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			w40.Add (this.buttonOk);
			global::Gtk.ButtonBox.ButtonBoxChild w42 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w40 [this.buttonOk]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 782;
			this.DefaultHeight = 197;
			this.Show ();
			this.buttonSpecificationsDirectoryPath.Clicked += new global::System.EventHandler (this.OnButtonSpecificationsDirectoryPathClicked);
			this.buttonResultsDirectoryPath.Clicked += new global::System.EventHandler (this.OnButtonResultsDirectoryPathClicked);
			this.buttonFixturesDirectoryPath.Clicked += new global::System.EventHandler (this.OnButtonFixturesDirectoryPathClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
